name: Deploy Expo VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd ~/hipster_ia_mobile_app
            git fetch origin
            git reset --hard origin/main
            tmux send-keys -t dev C-c
            tmux send-keys -t dev "cd ~/hipster_ia_mobile_app && EXPO_TUNNEL_SUBDOMAIN=hipsteria npx expo start --tunnel" Enter